### ISSUE TITLE
Err: chunk 0 pfs magic mismatch 0 vs 0x504634348

### ISSUE THREAD

**Issue by aqktjcm** [ApsaraDB/PolarDB-FileSystem#13]
when exec cmd `sudo pfs -C disk mkfs nvme1n11` , error reported as follows:

`Err: chunk 0 pfs magic mismatch 0 vs 0x504634348`

Code branch: `pfsd4pg-release`

**Comment by koperjian** [comment]
这块盘是否曾经格式化过，如果曾经格式化的话建议加上-f参数，强制格式化。。

**Comment by aqktjcm** [comment]
> [koperjian](/koperjian)



> 这块盘是否曾经格式化过，如果曾经格式化的话建议加上-f参数，强制格式化。。

@koperjian 没有格式化过

**Comment by koperjian** [comment]
试一下-f参数。

**Comment by aqktjcm** [comment]
> 试一下-f参数。

加上-f参数后报错也是一样的
![IMG_20220725_140409](https://user-images.githubusercontent.com/7100999/180710562-31a54df0-a0af-4a57-a009-d810c7305d17.jpg)

**Comment by koperjian** [comment]
你的sdc磁盘有多大？请保证磁盘要大于10G。最好是10G的整数倍。

**Comment by aqktjcm** [comment]
确实磁盘太 小引起的这个问题，改成大于10G的盘 后，问题解决。
